//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.0 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.05.11 at 11:17:38 AM CEST 
//


package nl.biggrid.plier.opm;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Observed Time allow for interval of observation, where an event is said to occur no earlier than a given time t1 and no later than a given time t2. When the event is observed to occur at a specific time, it is not convenient to use an interval. Instead, one can use the alternate exactlyAt attribute. We note that exactlyAt is disjoint from noEarlierThan and noLaterThan.
 * 
 * <p>Java class for OTime complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OTime">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *       &lt;/sequence>
 *       &lt;attribute name="exactlyAt" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="noEarlierThan" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *       &lt;attribute name="noLaterThan" type="{http://www.w3.org/2001/XMLSchema}dateTime" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OTime")
public class OTime {

    @XmlAttribute
    protected XMLGregorianCalendar exactlyAt;
    @XmlAttribute
    protected XMLGregorianCalendar noEarlierThan;
    @XmlAttribute
    protected XMLGregorianCalendar noLaterThan;

    /**
     * Gets the value of the exactlyAt property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExactlyAt() {
        return exactlyAt;
    }

    /**
     * Sets the value of the exactlyAt property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExactlyAt(XMLGregorianCalendar value) {
        this.exactlyAt = value;
    }

    /**
     * Gets the value of the noEarlierThan property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNoEarlierThan() {
        return noEarlierThan;
    }

    /**
     * Sets the value of the noEarlierThan property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNoEarlierThan(XMLGregorianCalendar value) {
        this.noEarlierThan = value;
    }

    /**
     * Gets the value of the noLaterThan property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getNoLaterThan() {
        return noLaterThan;
    }

    /**
     * Sets the value of the noLaterThan property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setNoLaterThan(XMLGregorianCalendar value) {
        this.noLaterThan = value;
    }

}
